<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="cfg" nsURI="http://com/cs/tu/analysis/cfg" nsPrefix="com.cs.tu.analysis.cfg">
    <eClassifiers xsi:type="ecore:EClass" name="MControlFlowGraph">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
          eType="#/0/AbstractNode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localVar" upperBound="-1"
          eType="#/0/Var" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mclass" lowerBound="1"
          eType="#/0/MClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="param" upperBound="-1"
          eType="#/0/Param" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="MLOC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractNode" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromNode" ordered="false"
          upperBound="-1" eType="#/0/AbstractNode" eOpposite="#/0/AbstractNode/toNode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toNode" ordered="false"
          eType="#/0/AbstractNode" eOpposite="#/0/AbstractNode/fromNode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="var" upperBound="-1"
          eType="#/0/Var" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlow" upperBound="-1"
          eType="#/0/AbstractNode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dUse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
          eType="#/0/Node" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#/0/AbstractNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalNode" eSuperTypes="#/0/AbstractNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="trueConditionNode" ordered="false"
          lowerBound="1" eType="#/0/Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="falseConditionNode" ordered="false"
          eType="#/0/Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
          eType="#/0/AbstractNode" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IterativeNode" eSuperTypes="#/0/AbstractNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="trueConditionNode" ordered="false"
          lowerBound="1" eType="#/0/Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="falseConditionNode" ordered="false"
          lowerBound="1" eType="#/0/Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
          eType="#/0/AbstractNode" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Var">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#/0/MControlFlowGraph"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInstant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocalVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="du" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="accessMethod" upperBound="-1"
          eType="#/0/MControlFlowGraph"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Param" eSuperTypes="#/0/Var"/>
    <eClassifiers xsi:type="ecore:EClass" name="MClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Method" lowerBound="1"
          upperBound="-1" eType="#/0/MControlFlowGraph" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instatVars" upperBound="-1"
          eType="#/0/Var" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="LCOM" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes"/>
</xmi:XMI>
