<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CFG" nsURI="http://com/cs/tu/findrefactor" nsPrefix="com.cs.tu.findrefactor">
  <eClassifiers xsi:type="ecore:EClass" name="MControlFlowGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AbstractNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localVar" upperBound="-1"
        eType="#//Var" containment="true" eOpposite="#//Var/method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromNode" ordered="false"
        upperBound="-1" eType="#//AbstractNode" eOpposite="#//AbstractNode/toNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toNode" ordered="false"
        eType="#//AbstractNode" eOpposite="#//AbstractNode/fromNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" upperBound="-1" eType="#//Var"
        containment="true" eOpposite="#//Var/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlow" upperBound="-1"
        eType="#//AbstractNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dUse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//AbstractNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalNode" eSuperTypes="#//AbstractNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trueConditionNode" ordered="false"
        lowerBound="1" eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falseConditionNode" ordered="false"
        lowerBound="1" eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IterativeNode" eSuperTypes="#//AbstractNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trueConditionNode" ordered="false"
        lowerBound="1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falseConditionNode" ordered="false"
        lowerBound="1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AbstractNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Var">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//MControlFlowGraph"
        eOpposite="#//MControlFlowGraph/localVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AbstractNode" eOpposite="#//AbstractNode/var"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param" eSuperTypes="#//Var"/>
</ecore:EPackage>
